default: &DEFAULT
  listen:
    interface: bee-$cam         # localhost is safest, if on same host
                                # as tron hub.
    port: 9103
  fee:
    port: /dev/ttyS1

  controllers: &CONTROLLERS
    all: [fee, ccd]
    starting: [fee, ccd]

$cam:
  <<: *DEFAULT
  
